<?php /* @var $this Rootd_Adminpage_Abstract */ ?>
<?php $activeTab    = $this->getActiveTab(); ?>
<?php $tabs         = $this->getTabs(); ?>
<div id="adminpage_<?php echo $this->getMenuSlug(); ?>" class="wrap">
    <h2><?php echo $this->getTitle(); ?></h2>
    <?php if (count($tabs)) : ?>
    <h2 class="nav-tab-wrapper" style="margin-bottom: 23px;">
        <?php foreach ($tabs as $tab) : ?>
        <?php if ($this->getTabState($tab)) : ?>
        <a href="<?php echo $this->getTabUrl($tab, $tab->getParams()); ?>" class="nav-tab<?php echo ($tab->getId() == $activeTab->getId()) ? ' nav-tab-active' : ''; ?>">
            <span><?php echo $tab->getTitle(); ?></span>
        </a>
        <?php endif; ?>
        <?php endforeach; ?>
    </h2>
    <?php foreach ($this->getMessages() as $type => $messages) : ?>
    <?php if (count($messages)) : ?>
    <div class="<?php echo $type; ?>">
        <?php foreach ($messages as $message) : ?>
        <p><?php echo $message; ?></p>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>
    <form method="post" action="<?php echo $this->getFormAction(); ?>" enctype="multipart/form-data">
        <?php //settings_fields('my_option_group'); ?>
        <?php //do_settings_sections($this->getMenuSlug()); ?>