<?php /* @var $this Rootd_Olark_Widget */ ?>
<?php $data = $this->getWidgetData(); ?>
<?php echo $data->getBeforeWidget(); ?>
<div class="olark-widget">
    <header>
        <?php echo $data->getBeforeTitle(); ?>
        <h4 class="widgettitle">
            <?php echo $data->getSidebarTitle(); ?>
        </h4>
        <?php echo $data->getAfterTitle(); ?>
    </header>
    <section>
        <?php echo $this->getOlarkHtml(); ?>
    </section>
</div>
<?php echo $data->getAfterWidget(); ?>